Hello, I am having issues installing the R package vegan in R/4.2.2-foss-2022b. It has to do with libRlapack.so not being linkable and I don't know what I can do with LAPACK on this HPC. Thanks.

[xgao32@atlas7-c10 Blood-type-GWAS]$ R

R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

- Project '/hpctmp/xgao32/Blood-type-GWAS' loaded. [renv 1.0.7]
- The project is out-of-sync -- use `renv::status()` for details.
Warning message:
renv took longer than expected (19 seconds) to activate the sandbox.

The sandbox can be disabled by setting:

    RENV_CONFIG_SANDBOX_ENABLED = FALSE

within an appropriate start-up .Renviron file.

See `?renv::config` for more details. 
> renv::install("vcfR")
# Downloading packages -------------------------------------------------------
- Downloading vcfR from CRAN ...                OK [file is up to date]
- Downloading vegan from CRAN ...               OK [file is up to date]
Successfully downloaded 2 packages in 8.6 seconds.

The following package(s) will be installed:
- memuse   [4.2-3]
- permute  [0.9-7]
- pinfsc50 [1.3.0]
- vcfR     [1.15.0]
- vegan    [2.6-8]
These packages will be installed into "/hpctmp/xgao32/Blood-type-GWAS/renv/library/R-4.2/x86_64-pc-linux-gnu".

Do you want to proceed? [Y/n]: y

# Installing packages --------------------------------------------------------
- Installing memuse ...                         OK [linked from cache]
- Installing pinfsc50 ...                       OK [linked from cache]
- Installing permute ...                        OK [linked from cache]
- Installing vegan ...                          FAILED
/nfs/app1/ebapps/arches/flat/software/R/4.2.2-foss-2022b/lib64/R/bin/R --vanilla -s -f '/tmp/RtmpJQqz07/renv-install-1c4d5795c1f.R'
================================================================================

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/hpctmp/xgao32/Blood-type-GWAS/renv/staging/2/vegan/libs/vegan.so':
  libRlapack.so: cannot open shared object file: No such file or directory
Calls: loadNamespace -> library.dynam -> dyn.load
Execution halted

Error: error testing if 'vegan' can be loaded [error code 1]
Traceback (most recent calls last):
13: renv::install("vcfR")
12: renv_install_impl(records)
11: renv_install_staged(records)
10: renv_install_default(records)
 9: handler(package, renv_install_package(record))
 8: renv_install_package(record)
 7: withCallingHandlers(renv_install_package_impl(record), error = function(e) writef("FAILED"))
 6: renv_install_package_impl(record)
 5: withCallingHandlers(if (isbin) renv_install_test(package), error = function(err) unlink(installpath, 
        recursive = TRUE))
 4: renv_install_test(package)
 3: renv_system_exec(command = R(), args = c("--vanilla", "-s", "-f", 
        renv_shell_path(script)), action = sprintf("testing if '%s' can be loaded", 
        package))
 2: abort(sprintf("error %s [error code %i]", action, status), body = renv_system_exec_details(command, 
        args, output))
 1: stop(fallback)

```{R}


```